# Generated by Django 5.1.4 on 2025-01-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_meuusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeuUsuario',
        ),
    ]
